export const COLORS = {
  primary: '#16A34A',
  primaryDark: '#14532D',
  primaryMid: '#166534',
  primaryLight: '#BBF7D0',
  primaryBg: '#F0FDF4',
  gold: '#D97706',
  goldLight: '#FEF3C7',
  secondary: '#16A34A',
  secondaryLight: '#DCFCE7',
  error: '#DC2626',
  errorLight: '#FEE2E2',
  warning: '#D97706',
  warningLight: '#FEF3C7',
  info: '#2563EB',
  infoLight: '#DBEAFE',
  white: '#FFFFFF',
  black: '#000000',
  text: '#1C1917',
  textSecondary: '#57534E',
  textMuted: '#A8A29E',
  border: '#D1FAE5',
  borderLight: '#F0FDF4',
  surface: '#FFFFFF',
  background: '#F8FAFC',
  pending: '#D97706',
  pendingBg: '#FEF3C7',
  approved: '#16A34A',
  approvedBg: '#DCFCE7',
  rejected: '#DC2626',
  rejectedBg: '#FEE2E2',
};

export const FONT_SIZE = {
  xs: 11,
  sm: 13,
  base: 15,
  lg: 17,
  xl: 19,
  '2xl': 22,
  '3xl': 28,
  '4xl': 34,
};

export const RADIUS = {
  sm: 6,
  md: 10,
  lg: 14,
  xl: 20,
  full: 999,
};

export const SHADOW = {
  sm: {
    shadowColor: '#166534',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  md: {
    shadowColor: '#166534',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
};

export const T: Record<string, Record<string, string>> = {
  en: {
    appName: 'Krushi Suvidha',
    appNameHi: 'कृषी सुविधा',
    tagline: 'Your farm. Your rights. Your government.',
    getStarted: 'Get Started',
    selectLang: 'Select Language',
    mobileNumber: 'Mobile Number',
    enterMobile: 'Enter 10-digit mobile number',
    sendOtp: 'Send OTP',
    otpSentTo: 'OTP sent to',
    enterOtp: 'Enter 6-digit OTP',
    verify: 'Verify & Continue',
    resendOtp: 'Resend OTP',
    resendIn: 'Resend in',
    seconds: 's',
    registerTitle: 'Farmer Registration',
    registerSubtitle: 'Upload 5 documents to register. Our AI extracts your details automatically.',
    uploadDocs: 'Document Upload Progress',
    uploadDoc: 'Upload',
    reUpload: 'Re-upload',
    processing: 'Processing...',
    uploaded: 'Uploaded ✓',
    failed: 'Failed — Tap to retry',
    submitReg: 'Submit Registration',
    submitting: 'Submitting…',
    pendingTitle: 'Application Under Review',
    pendingSubtitle: 'Your documents have been submitted. The agriculture officer will verify your details.',
    farmerId: 'Farmer ID',
    docsSubmitted: 'Documents Submitted',
    refreshStatus: 'Refresh Status',
    statusSubmitted: 'Documents Submitted',
    statusUnderReview: 'Under Review',
    statusDecision: 'Admin Decision',
    home: 'Home',
    schemes: 'Schemes',
    notifications: 'Alerts',
    profile: 'Profile',
    analytics: 'Analytics',
    welcome: 'Namaste',
    activeStatus: 'Verified Farmer ✓',
    farmSummary: 'Farm Summary',
    totalLand: 'Total Land',
    primaryCrop: 'Primary Crop',
    location: 'Location',
    district: 'District',
    quickActions: 'Quick Actions',
    applyScheme: 'Apply for Scheme',
    fileInsurance: 'Insurance Claim',
    raiseGrievance: 'Raise Grievance',
    checkSubsidy: 'Check Subsidy',
    recentNotifs: 'Recent Alerts',
    viewAll: 'View All',
    availableSchemes: 'Available Schemes',
    centralScheme: 'Central',
    stateScheme: 'State',
    active: 'Active',
    closed: 'Closed',
    knowMore: 'Know More',
    noSchemes: 'No schemes available',
    noNotifications: 'No notifications yet',
    markAllRead: 'Mark all read',
    myProfile: 'My Profile',
    kycVerified: 'KYC Verified',
    personalInfo: 'Personal Details',
    landInfo: 'Land Details',
    bankInfo: 'Bank Details',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    cancel: 'Cancel',
    name: 'Name',
    aadhaar: 'Aadhaar No.',
    dob: 'Date of Birth',
    gender: 'Gender',
    mobile: 'Mobile',
    village: 'Village',
    taluka: 'Taluka',
    surveyNo: 'Survey No.',
    landArea: 'Land Area',
    crop: 'Crop',
    bank: 'Bank',
    branch: 'Branch',
    ifsc: 'IFSC Code',
    accountNo: 'Account No.',
    notAvailable: 'Not available',
    na: '—',
    back: 'Back',
    loading: 'Loading…',
  },
  hi: {
    appName: 'कृषी सुविधा',
    appNameHi: 'कृषी सुविधा',
    tagline: 'आपका खेत। आपके अधिकार। आपकी सरकार।',
    getStarted: 'शुरू करें',
    selectLang: 'भाषा चुनें',
    mobileNumber: 'मोबाइल नंबर',
    enterMobile: '10 अंकों का मोबाइल नंबर दर्ज करें',
    sendOtp: 'OTP भेजें',
    otpSentTo: 'OTP भेजा गया',
    enterOtp: '6 अंकों का OTP दर्ज करें',
    verify: 'सत्यापित करें',
    resendOtp: 'OTP दोबारा भेजें',
    resendIn: 'में भेजें',
    seconds: 'सेकंड',
    registerTitle: 'किसान पंजीकरण',
    registerSubtitle: '5 दस्तावेज़ अपलोड करें। हमारा सिस्टम आपकी जानकारी स्वचालित रूप से निकालेगा।',
    uploadDocs: 'दस्तावेज़ अपलोड प्रगति',
    uploadDoc: 'अपलोड',
    reUpload: 'फिर से अपलोड',
    processing: 'प्रोसेसिंग...',
    uploaded: 'अपलोड हुआ ✓',
    failed: 'विफल — पुनः प्रयास करें',
    submitReg: 'पंजीकरण सबमिट करें',
    submitting: 'सबमिट हो रहा है…',
    pendingTitle: 'आवेदन समीक्षाधीन',
    pendingSubtitle: 'आपके दस्तावेज़ सबमिट हो गए हैं। कृषि अधिकारी आपके विवरण की समीक्षा करेंगे।',
    farmerId: 'किसान ID',
    docsSubmitted: 'सबमिट किए गए दस्तावेज़',
    refreshStatus: 'स्थिति अपडेट करें',
    statusSubmitted: 'दस्तावेज़ सबमिट',
    statusUnderReview: 'समीक्षाधीन',
    statusDecision: 'अधिकारी निर्णय',
    home: 'होम',
    schemes: 'योजनाएं',
    notifications: 'सूचनाएं',
    profile: 'प्रोफ़ाइल',
    analytics: 'विश्लेषण',
    welcome: 'नमस्ते',
    activeStatus: 'सत्यापित किसान ✓',
    farmSummary: 'खेत सारांश',
    totalLand: 'कुल भूमि',
    primaryCrop: 'प्राथमिक फसल',
    location: 'स्थान',
    district: 'जिला',
    quickActions: 'त्वरित कार्य',
    applyScheme: 'योजना के लिए आवेदन',
    fileInsurance: 'बीमा दावा',
    raiseGrievance: 'शिकायत दर्ज करें',
    checkSubsidy: 'सब्सिडी जांचें',
    recentNotifs: 'हालिया सूचनाएं',
    viewAll: 'सभी देखें',
    availableSchemes: 'उपलब्ध योजनाएं',
    centralScheme: 'केंद्रीय',
    stateScheme: 'राज्य',
    active: 'सक्रिय',
    closed: 'बंद',
    knowMore: 'अधिक जानें',
    noSchemes: 'कोई योजना उपलब्ध नहीं',
    noNotifications: 'कोई सूचना नहीं',
    markAllRead: 'सभी पढ़े हुए करें',
    myProfile: 'मेरी प्रोफ़ाइल',
    kycVerified: 'KYC सत्यापित',
    personalInfo: 'व्यक्तिगत विवरण',
    landInfo: 'भूमि विवरण',
    bankInfo: 'बैंक विवरण',
    logout: 'लॉगआउट',
    logoutConfirm: 'क्या आप लॉगआउट करना चाहते हैं?',
    cancel: 'रद्द करें',
    name: 'नाम',
    aadhaar: 'आधार नं.',
    dob: 'जन्म तिथि',
    gender: 'लिंग',
    mobile: 'मोबाइल',
    village: 'गाँव',
    taluka: 'तहसील',
    surveyNo: 'सर्वे नं.',
    landArea: 'भूमि क्षेत्र',
    crop: 'फसल',
    bank: 'बैंक',
    branch: 'शाखा',
    ifsc: 'IFSC कोड',
    accountNo: 'खाता नं.',
    notAvailable: 'उपलब्ध नहीं',
    na: '—',
    back: 'वापस',
    loading: 'लोड हो रहा है…',
    district: 'जिला',
  },
  mr: {
    appName: 'कृषी सुविधा',
    appNameHi: 'कृषी सुविधा',
    tagline: 'तुमचं शेत. तुमचे हक्क. तुमचं सरकार.',
    getStarted: 'सुरू करा',
    selectLang: 'भाषा निवडा',
    mobileNumber: 'मोबाइल नंबर',
    enterMobile: '10 अंकी मोबाइल नंबर टाका',
    sendOtp: 'OTP पाठवा',
    otpSentTo: 'OTP पाठवला',
    enterOtp: '6 अंकी OTP टाका',
    verify: 'सत्यापित करा',
    resendOtp: 'OTP पुन्हा पाठवा',
    resendIn: 'पाठवा',
    seconds: 'सेकंद',
    registerTitle: 'शेतकरी नोंदणी',
    registerSubtitle: '5 कागदपत्रे अपलोड करा. आमची AI प्रणाली तुमची माहिती आपोआप काढेल.',
    uploadDocs: 'कागदपत्र अपलोड प्रगती',
    uploadDoc: 'अपलोड',
    reUpload: 'पुन्हा अपलोड',
    processing: 'प्रक्रिया सुरू आहे...',
    uploaded: 'अपलोड झाले ✓',
    failed: 'अयशस्वी — पुन्हा प्रयत्न करा',
    submitReg: 'नोंदणी सबमिट करा',
    submitting: 'सबमिट होत आहे…',
    pendingTitle: 'अर्ज पुनरावलोकनाधीन',
    pendingSubtitle: 'तुमचे कागदपत्र सबमिट झाले आहेत. कृषी अधिकारी तपासणी करतील.',
    farmerId: 'शेतकरी ID',
    docsSubmitted: 'सबमिट केलेले कागदपत्र',
    refreshStatus: 'स्थिती अपडेट करा',
    statusSubmitted: 'कागदपत्र सबमिट',
    statusUnderReview: 'पुनरावलोकनाधीन',
    statusDecision: 'अधिकारी निर्णय',
    home: 'होम',
    schemes: 'योजना',
    notifications: 'सूचना',
    profile: 'प्रोफाइल',
    analytics: 'विश्लेषण',
    welcome: 'नमस्कार',
    activeStatus: 'सत्यापित शेतकरी ✓',
    farmSummary: 'शेत सारांश',
    totalLand: 'एकूण जमीन',
    primaryCrop: 'प्राथमिक पीक',
    location: 'स्थान',
    district: 'जिल्हा',
    quickActions: 'त्वरित क्रिया',
    applyScheme: 'योजनेसाठी अर्ज',
    fileInsurance: 'विमा दावा',
    raiseGrievance: 'तक्रार नोंदवा',
    checkSubsidy: 'अनुदान तपासा',
    recentNotifs: 'अलीकडील सूचना',
    viewAll: 'सर्व पहा',
    availableSchemes: 'उपलब्ध योजना',
    centralScheme: 'केंद्रीय',
    stateScheme: 'राज्य',
    active: 'सक्रिय',
    closed: 'बंद',
    knowMore: 'अधिक जाणा',
    noSchemes: 'कोणतीही योजना उपलब्ध नाही',
    noNotifications: 'कोणतीही सूचना नाही',
    markAllRead: 'सर्व वाचलेले करा',
    myProfile: 'माझे प्रोफाइल',
    kycVerified: 'KYC सत्यापित',
    personalInfo: 'वैयक्तिक तपशील',
    landInfo: 'जमीन तपशील',
    bankInfo: 'बँक तपशील',
    logout: 'लॉगआउट',
    logoutConfirm: 'तुम्हाला लॉगआउट करायचे आहे का?',
    cancel: 'रद्द करा',
    name: 'नाव',
    aadhaar: 'आधार क्र.',
    dob: 'जन्मतारीख',
    gender: 'लिंग',
    mobile: 'मोबाइल',
    village: 'गाव',
    taluka: 'तालुका',
    surveyNo: 'भूमापन क्र.',
    landArea: 'जमीन क्षेत्र',
    crop: 'पीक',
    bank: 'बँक',
    branch: 'शाखा',
    ifsc: 'IFSC कोड',
    accountNo: 'खाते क्र.',
    notAvailable: 'उपलब्ध नाही',
    na: '—',
    back: 'मागे',
    loading: 'लोड होत आहे…',
  },
};

export function useT(lang: string): (key: string) => string {
  const map = T[lang] ?? T['en'];
  return (key: string) => map[key] ?? T['en'][key] ?? key;
}
